// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXicpQBd4LiyAVYA3CKxYxpZQ_r5-iUDc',
    appId: '1:675975924362:web:d8f7e5343ff21f8c567b73',
    messagingSenderId: '675975924362',
    projectId: 'inferno-app-dbdb0',
    authDomain: 'inferno-app-dbdb0.firebaseapp.com',
    databaseURL: 'https://inferno-app-dbdb0-default-rtdb.firebaseio.com',
    storageBucket: 'inferno-app-dbdb0.appspot.com',
    measurementId: 'G-Z44J3P373B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTbh13ULv33QwdMz5kO8vrHGWrTJOidOs',
    appId: '1:675975924362:android:fea5e2887e36d2df567b73',
    messagingSenderId: '675975924362',
    projectId: 'inferno-app-dbdb0',
    databaseURL: 'https://inferno-app-dbdb0-default-rtdb.firebaseio.com',
    storageBucket: 'inferno-app-dbdb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRDwradON3WXa0nxqThkfYnh9UTPUdHRc',
    appId: '1:675975924362:ios:536dda665e233637567b73',
    messagingSenderId: '675975924362',
    projectId: 'inferno-app-dbdb0',
    databaseURL: 'https://inferno-app-dbdb0-default-rtdb.firebaseio.com',
    storageBucket: 'inferno-app-dbdb0.appspot.com',
    androidClientId: '675975924362-569vjha19k7mdi9cpj0govfvhk273quo.apps.googleusercontent.com',
    iosClientId: '675975924362-50r2c826ub6s4bi17a7ihsgqnfa95752.apps.googleusercontent.com',
    iosBundleId: 'com.senkwa.inferno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRDwradON3WXa0nxqThkfYnh9UTPUdHRc',
    appId: '1:675975924362:ios:3d19691c2970d1ae567b73',
    messagingSenderId: '675975924362',
    projectId: 'inferno-app-dbdb0',
    databaseURL: 'https://inferno-app-dbdb0-default-rtdb.firebaseio.com',
    storageBucket: 'inferno-app-dbdb0.appspot.com',
    androidClientId: '675975924362-569vjha19k7mdi9cpj0govfvhk273quo.apps.googleusercontent.com',
    iosClientId: '675975924362-eikkdql2ub3ssisg20ed3aku4jmltri9.apps.googleusercontent.com',
    iosBundleId: 'com.senkw.inferno',
  );
}
